In [134]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Series

In [135]:
np.random.seed(42)
arr_int1 = np.random.randint(100, 10000, 100)
arr_int1.shape

(100,)

In [136]:
sr = pd.Series(arr_int1)
# sr

Seriesとndarry

In [137]:
type(sr)

pandas.core.series.Series

In [138]:
sr.ndim

1

In [139]:
sr.shape

(100,)

In [140]:
sr.max()

9792

Seriesに名前を付ける

In [141]:
sr.name = "Price"

In [142]:
sr_price = pd.Series(arr_int1, name="Price")
sr_price

0     7370
1      960
2     5490
3     5291
4     5834
      ... 
95     491
96    5992
97    3661
98    6284
99    3199
Name: Price, Length: 100, dtype: int32

10-100の整数データ(size=100)からSeriesを作成

In [143]:
arr_int2 = np.random.randint(10, 100, 100)
sr_quantity = pd.Series(arr_int2, name="Quantity")

0-10の小数データ(100, 2)からDFを作成    

In [144]:
arr_fl = np.random.rand(100, 2) * 10
# print(arr_fl)

In [145]:
df = pd.DataFrame(arr_fl)
df

0         1
0   2.420553  6.721355
1   7.616196  2.376375
2   7.282163  3.677831
3   6.323058  6.335297
4   5.357747  0.902898
..       ...       ...
95  6.158501  6.350937
96  0.453040  3.746126
97  6.258599  5.031363
98  8.564898  6.586936
99  1.629344  0.705687

[100 rows x 2 columns]

In [146]:
df_wh = pd.DataFrame(arr_fl, columns=["Width", "Height"])
df_wh

Width    Height
0   2.420553  6.721355
1   7.616196  2.376375
2   7.282163  3.677831
3   6.323058  6.335297
4   5.357747  0.902898
..       ...       ...
95  6.158501  6.350937
96  0.453040  3.746126
97  6.258599  5.031363
98  8.564898  6.586936
99  1.629344  0.705687

[100 rows x 2 columns]

40-60の範囲の一様分布の少数データ(100, 1)からDFを作成

In [147]:
arr_uni = np.random.uniform(40, 60, 100)
df_quality = pd.DataFrame(arr_uni, columns=["Quality"])
df_quality

Quality
0   52.848386
1   40.530226
2   51.715512
3   58.804605
4   51.509484
..        ...
95  55.542938
96  51.168085
97  48.484440
98  58.127088
99  42.223950

[100 rows x 1 columns]

NormDist(mean=0, std=1)に従う小数データ(100, 1)からDFを作成

In [148]:
arr_norm = np.random.normal(loc=0, scale=1, size=(100, 1))
df_difference = pd.DataFrame(arr_norm, columns=["Difference"])
df_difference

Difference
0    -0.302324
1    -0.004563
2    -0.682343
3    -0.048195
4     1.271138
..         ...
95   -0.075304
96   -1.101252
97    0.487673
98    0.747368
99   -0.290692

[100 rows x 1 columns]

['red', 'green', 'blue'](100, 1), ['circle', 'square', 'triangle'](100, 1), ndarryを結合しDataFrameを作成

In [149]:
colors = ['red', 'green', 'blue']
shapes = ['circle', 'square', 'triangle']

arr_colors = np.random.choice(colors, size=(100, 1))
arr_shapes = np.random.choice(shapes, size=(100, 1))

arr_cs = np.concatenate([arr_colors, arr_shapes], axis=1)
arr_cs_hstack = np.hstack([arr_colors, arr_shapes])
arr_cs_vstack = np.vstack([arr_colors, arr_shapes])


In [150]:
df_cs = pd.DataFrame(arr_cs, columns=["Colors", "Shape"])
df_cs

Colors     Shape
0    blue    circle
1    blue    circle
2     red    square
3   green    square
4     red    square
..    ...       ...
95  green    square
96   blue    square
97    red    circle
98   blue  triangle
99  green    circle

[100 rows x 2 columns]

datetime 1977/7/5から1日刻み(100, 1)からDatetimeIndex, Seriesを作成

In [151]:
dates = pd.date_range('1997/7/5', periods=100, freq="D")
sr_date = pd.Series(dates, name="Date")
sr_date

0    1997-07-05
1    1997-07-06
2    1997-07-07
3    1997-07-08
4    1997-07-09
        ...    
95   1997-10-08
96   1997-10-09
97   1997-10-10
98   1997-10-11
99   1997-10-12
Name: Date, Length: 100, dtype: datetime64[ns]

Series, DataFrameを結合

In [152]:
df = pd.concat([sr_date, sr_price, sr_quantity, df_wh, df_quality, df_difference], axis=1)

In [153]:
df.sample(3)

Date  Price  Quantity     Width    Height    Quality  Difference
49 1997-08-23   9770        15  3.169220  1.694927  46.400992   -0.055485
65 1997-09-08   1095        81  0.359423  4.655980  55.831581    1.551263
56 1997-08-30   3173        84  7.024841  3.594912  59.001239   -1.368590

# 変換

Series, DataFrameをndarryに変換

In [154]:
df.Price.values

array([7370,  960, 5490, 5291, 5834, 6365,  566, 4526, 5678, 8422, 1785,
        869, 7049, 2533, 5411, 5151, 6520, 1284, 4655, 3485, 6496, 8766,
       9374, 2658, 7949, 2147, 2847, 9267,  289, 2834, 3105, 4758, 1999,
       7834, 1367, 1628, 3656, 3990, 8938, 5493, 8892, 8533, 7613, 2712,
       7141, 9655, 6335, 5586, 7199, 9770,  875, 8326, 3252, 1685, 4043,
       7655, 3173, 1121, 3943, 8089, 9792, 6973, 5775,  261, 4397, 1095,
       7729, 9567, 1116, 7969, 6539, 7992, 6963, 8016, 8629,  978, 9368,
       4987, 4959, 6431, 8671, 8784, 7308, 5376, 2162,  164, 8106, 2668,
       5563, 2127, 2795, 9787, 5358, 5718, 6836,  491, 5992, 3661, 6284,
       3199])

Series, DataFrameをndarryに変換

In [155]:
#列ごとに取り出す
df["Price"].values

array([7370,  960, 5490, 5291, 5834, 6365,  566, 4526, 5678, 8422, 1785,
        869, 7049, 2533, 5411, 5151, 6520, 1284, 4655, 3485, 6496, 8766,
       9374, 2658, 7949, 2147, 2847, 9267,  289, 2834, 3105, 4758, 1999,
       7834, 1367, 1628, 3656, 3990, 8938, 5493, 8892, 8533, 7613, 2712,
       7141, 9655, 6335, 5586, 7199, 9770,  875, 8326, 3252, 1685, 4043,
       7655, 3173, 1121, 3943, 8089, 9792, 6973, 5775,  261, 4397, 1095,
       7729, 9567, 1116, 7969, 6539, 7992, 6963, 8016, 8629,  978, 9368,
       4987, 4959, 6431, 8671, 8784, 7308, 5376, 2162,  164, 8106, 2668,
       5563, 2127, 2795, 9787, 5358, 5718, 6836,  491, 5992, 3661, 6284,
       3199])

In [156]:
#行ごとに取り出す
df.values[:2]

array([[Timestamp('1997-07-05 00:00:00'), 7370, 16, 2.4205527151150044,
        6.721355474058786, 52.84838556412631, -0.3023242420763079],
       [Timestamp('1997-07-06 00:00:00'), 960, 82, 7.616196153287175,
        2.3763754399239967, 40.53022621083244, -0.004562828990296256]],
      dtype=object)

Series, DataFrameをlistに変換

In [157]:
#列をリストに変換
df.Price.tolist()[:5]

[7370, 960, 5490, 5291, 5834]

In [158]:
df.values.tolist()[:2]

[[Timestamp('1997-07-05 00:00:00'),
  7370,
  16,
  2.4205527151150044,
  6.721355474058786,
  52.84838556412631,
  -0.3023242420763079],
 [Timestamp('1997-07-06 00:00:00'),
  960,
  82,
  7.616196153287175,
  2.3763754399239967,
  40.53022621083244,
  -0.004562828990296256]]

Series, DataFrameをdictionaryに変換

In [159]:
df.Price.to_dict()

{0: 7370,
 1: 960,
 2: 5490,
 3: 5291,
 4: 5834,
 5: 6365,
 6: 566,
 7: 4526,
 8: 5678,
 9: 8422,
 10: 1785,
 11: 869,
 12: 7049,
 13: 2533,
 14: 5411,
 15: 5151,
 16: 6520,
 17: 1284,
 18: 4655,
 19: 3485,
 20: 6496,
 21: 8766,
 22: 9374,
 23: 2658,
 24: 7949,
 25: 2147,
 26: 2847,
 27: 9267,
 28: 289,
 29: 2834,
 30: 3105,
 31: 4758,
 32: 1999,
 33: 7834,
 34: 1367,
 35: 1628,
 36: 3656,
 37: 3990,
 38: 8938,
 39: 5493,
 40: 8892,
 41: 8533,
 42: 7613,
 43: 2712,
 44: 7141,
 45: 9655,
 46: 6335,
 47: 5586,
 48: 7199,
 49: 9770,
 50: 875,
 51: 8326,
 52: 3252,
 53: 1685,
 54: 4043,
 55: 7655,
 56: 3173,
 57: 1121,
 58: 3943,
 59: 8089,
 60: 9792,
 61: 6973,
 62: 5775,
 63: 261,
 64: 4397,
 65: 1095,
 66: 7729,
 67: 9567,
 68: 1116,
 69: 7969,
 70: 6539,
 71: 7992,
 72: 6963,
 73: 8016,
 74: 8629,
 75: 978,
 76: 9368,
 77: 4987,
 78: 4959,
 79: 6431,
 80: 8671,
 81: 8784,
 82: 7308,
 83: 5376,
 84: 2162,
 85: 164,
 86: 8106,
 87: 2668,
 88: 5563,
 89: 2127,
 90: 2795,
 91: 9787,
 92: 5

In [160]:
df.to_dict()

{'Date': {0: Timestamp('1997-07-05 00:00:00'),
  1: Timestamp('1997-07-06 00:00:00'),
  2: Timestamp('1997-07-07 00:00:00'),
  3: Timestamp('1997-07-08 00:00:00'),
  4: Timestamp('1997-07-09 00:00:00'),
  5: Timestamp('1997-07-10 00:00:00'),
  6: Timestamp('1997-07-11 00:00:00'),
  7: Timestamp('1997-07-12 00:00:00'),
  8: Timestamp('1997-07-13 00:00:00'),
  9: Timestamp('1997-07-14 00:00:00'),
  10: Timestamp('1997-07-15 00:00:00'),
  11: Timestamp('1997-07-16 00:00:00'),
  12: Timestamp('1997-07-17 00:00:00'),
  13: Timestamp('1997-07-18 00:00:00'),
  14: Timestamp('1997-07-19 00:00:00'),
  15: Timestamp('1997-07-20 00:00:00'),
  16: Timestamp('1997-07-21 00:00:00'),
  17: Timestamp('1997-07-22 00:00:00'),
  18: Timestamp('1997-07-23 00:00:00'),
  19: Timestamp('1997-07-24 00:00:00'),
  20: Timestamp('1997-07-25 00:00:00'),
  21: Timestamp('1997-07-26 00:00:00'),
  22: Timestamp('1997-07-27 00:00:00'),
  23: Timestamp('1997-07-28 00:00:00'),
  24: Timestamp('1997-07-29 00:00:00'),
  

In [161]:
df.to_dict(orient="records")

[{'Date': Timestamp('1997-07-05 00:00:00'),
  'Price': 7370,
  'Quantity': 16,
  'Width': 2.4205527151150044,
  'Height': 6.721355474058786,
  'Quality': 52.84838556412631,
  'Difference': -0.3023242420763079},
 {'Date': Timestamp('1997-07-06 00:00:00'),
  'Price': 960,
  'Quantity': 82,
  'Width': 7.616196153287175,
  'Height': 2.3763754399239967,
  'Quality': 40.53022621083244,
  'Difference': -0.004562828990296256},
 {'Date': Timestamp('1997-07-07 00:00:00'),
  'Price': 5490,
  'Quantity': 81,
  'Width': 7.282163486118596,
  'Height': 3.677831327192532,
  'Quality': 51.71551162546926,
  'Difference': -0.6823426011201539},
 {'Date': Timestamp('1997-07-08 00:00:00'),
  'Price': 5291,
  'Quantity': 21,
  'Width': 6.3230583059357945,
  'Height': 6.335297107608947,
  'Quality': 58.80460482849915,
  'Difference': -0.04819548553581296},
 {'Date': Timestamp('1997-07-09 00:00:00'),
  'Price': 5834,
  'Quantity': 43,
  'Width': 5.357746840747585,
  'Height': 0.902897700544083,
  'Quality': 51

Seriesの作成

In [162]:
arr = np.random.randint(0, 100, 8)
sr = pd.Series(arr, name="sample", index=list("ABCDEFGH"))

In [163]:
dict_from_sr = sr.to_dict()
pd.Series(dict_from_sr, name="sample")

A    10
B    73
C    37
D     5
E    71
F    22
G    46
H    89
Name: sample, dtype: int64

DataFrameの作成

In [164]:
pd.DataFrame([{"A": 1, "B": 2, "C": 3}, {"A": 10, "B": 20, "C": 30}], index=["math", "english"])

A   B   C
math      1   2   3
english  10  20  30

In [165]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
pd.DataFrame([arr1, arr2])

0         1         2         3         4         5         6  \
0  0.947283  0.153351  0.586230  0.505889  0.611454  0.018110  0.872124   
1  0.922499  0.707239  0.152539  0.576288  0.606715  0.424131  0.736444   

          7         8         9  
0  0.932118  0.565133  0.696651  
1  0.934367  0.925569  0.450839

# DataFrameの情報取得

df.info(): null, dtypeなど

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Date        100 non-null    datetime64[ns]
 1   Price       100 non-null    int32         
 2   Quantity    100 non-null    int32         
 3   Width       100 non-null    float64       
 4   Height      100 non-null    float64       
 5   Quality     100 non-null    float64       
 6   Difference  100 non-null    float64       
dtypes: datetime64[ns](1), float64(4), int32(2)
memory usage: 4.8 KB


df.sum(): 要素の合計

In [167]:
df.sum(axis=0)

C:\Users\kirit\AppData\Local\Temp\ipykernel_15872\3976943683.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.sum(axis=0)


Price         520823.000000
Quantity        5337.000000
Width            484.304895
Height           515.360765
Quality         5041.882296
Difference        12.035446
dtype: float64

In [168]:
df.sum(numeric_only=True)

Price         520823.000000
Quantity        5337.000000
Width            484.304895
Height           515.360765
Quality         5041.882296
Difference        12.035446
dtype: float64

In [169]:
df.select_dtypes(include=["int", "float"]).sum()

Price         520823.000000
Quantity        5337.000000
Width            484.304895
Height           515.360765
Quality         5041.882296
Difference        12.035446
dtype: float64

# IndexとColumnについて

indexとcolumnsの取得

In [170]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [171]:
df.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int64)

In [172]:
pd.RangeIndex(start=1, stop=20, step=4).values

array([ 1,  5,  9, 13, 17], dtype=int64)

In [173]:
df.columns

Index(['Date', 'Price', 'Quantity', 'Width', 'Height', 'Quality',
       'Difference'],
      dtype='object')

indexの設定とリセット

In [174]:
df.head(3)

Date  Price  Quantity     Width    Height    Quality  Difference
0 1997-07-05   7370        16  2.420553  6.721355  52.848386   -0.302324
1 1997-07-06    960        82  7.616196  2.376375  40.530226   -0.004563
2 1997-07-07   5490        81  7.282163  3.677831  51.715512   -0.682343

In [175]:
# カラムの一つをindexに設定する
df.set_index("Date", inplace=True)

In [176]:
df.head(3)

Price  Quantity     Width    Height    Quality  Difference
Date                                                                  
1997-07-05   7370        16  2.420553  6.721355  52.848386   -0.302324
1997-07-06    960        82  7.616196  2.376375  40.530226   -0.004563
1997-07-07   5490        81  7.282163  3.677831  51.715512   -0.682343

In [177]:
df.reset_index(inplace=True)
df.head(3)

Date  Price  Quantity     Width    Height    Quality  Difference
0 1997-07-05   7370        16  2.420553  6.721355  52.848386   -0.302324
1 1997-07-06    960        82  7.616196  2.376375  40.530226   -0.004563
2 1997-07-07   5490        81  7.282163  3.677831  51.715512   -0.682343

index label, column labelの変更

In [178]:
cols = df.columns
cols

Index(['Date', 'Price', 'Quantity', 'Width', 'Height', 'Quality',
       'Difference'],
      dtype='object')

In [179]:
df.rename(index={0: "ZERO"}, columns={"Date": "Time"}).head(3)

Time  Price  Quantity     Width    Height    Quality  Difference
ZERO 1997-07-05   7370        16  2.420553  6.721355  52.848386   -0.302324
1    1997-07-06    960        82  7.616196  2.376375  40.530226   -0.004563
2    1997-07-07   5490        81  7.282163  3.677831  51.715512   -0.682343

In [180]:
df.index = np.arange(100, 200)
df.columns = list("ABCDEFG")
df.head(3)

A     B   C         D         E          F         G
100 1997-07-05  7370  16  2.420553  6.721355  52.848386 -0.302324
101 1997-07-06   960  82  7.616196  2.376375  40.530226 -0.004563
102 1997-07-07  5490  81  7.282163  3.677831  51.715512 -0.682343

In [181]:
df = df.add_prefix("#")
df.head(3)

#A    #B  #C        #D        #E         #F        #G
100 1997-07-05  7370  16  2.420553  6.721355  52.848386 -0.302324
101 1997-07-06   960  82  7.616196  2.376375  40.530226 -0.004563
102 1997-07-07  5490  81  7.282163  3.677831  51.715512 -0.682343

In [182]:
df.reset_index(inplace=True, drop=True)
df.head(3)

#A    #B  #C        #D        #E         #F        #G
0 1997-07-05  7370  16  2.420553  6.721355  52.848386 -0.302324
1 1997-07-06   960  82  7.616196  2.376375  40.530226 -0.004563
2 1997-07-07  5490  81  7.282163  3.677831  51.715512 -0.682343

In [183]:
df.columns = cols
df.head(3)

Date  Price  Quantity     Width    Height    Quality  Difference
0 1997-07-05   7370        16  2.420553  6.721355  52.848386   -0.302324
1 1997-07-06    960        82  7.616196  2.376375  40.530226   -0.004563
2 1997-07-07   5490        81  7.282163  3.677831  51.715512   -0.682343

# 欠損値

None, null, npnanを確認

In [185]:
print(None)
print(np.nan)

None
nan


DataFrameの欠損値はNoneもしくはnp.nanで置き換える

In [190]:
null_value = [None, np.nan]

In [ ]:
for i in range(30):
    np.random.seed(i)
    s = np.random.randint(100)
    t = np.random.randint(0, 7)
    df.iloc[s, t] = np.random.choice(null_value)