- dimention
- shape
- size
- conversion of shape

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
arr1 = np.random.rand(2, 3, 4)
print(arr1)

[[[0.7644521  0.78063276 0.21883728 0.81353175]
  [0.03745279 0.70097225 0.41451578 0.1774552 ]
  [0.87102949 0.30129072 0.30144186 0.02473647]]

 [[0.07888593 0.23394314 0.44573598 0.62764174]
  [0.67311841 0.94027639 0.81711576 0.44493148]
  [0.00884996 0.71093197 0.84538595 0.1071392 ]]]


dimention

In [4]:
arr1.ndim

3

In [7]:
np.random.rand(2, 3, 4, 5, 6).ndim

5

shape

In [9]:
arr2 = np.random.rand(2, 3, 4)

In [10]:
arr2.shape

(2, 3, 4)

形状の変換

In [13]:
arr2.reshape(2, 4, 3)

array([[[0.31764645, 0.23238274, 0.22545205],
        [0.57565687, 0.87041814, 0.81164125],
        [0.35971101, 0.29264853, 0.4908483 ],
        [0.32953749, 0.17314029, 0.23005575]],

       [[0.41789226, 0.63786224, 0.22180447],
        [0.66236618, 0.21132681, 0.70819676],
        [0.80546665, 0.58719367, 0.19307051],
        [0.84459973, 0.83520487, 0.10906692]]])

In [16]:
arr2.reshape(1, -1)

array([[0.31764645, 0.23238274, 0.22545205, 0.57565687, 0.87041814,
        0.81164125, 0.35971101, 0.29264853, 0.4908483 , 0.32953749,
        0.17314029, 0.23005575, 0.41789226, 0.63786224, 0.22180447,
        0.66236618, 0.21132681, 0.70819676, 0.80546665, 0.58719367,
        0.19307051, 0.84459973, 0.83520487, 0.10906692]])

演算例

In [27]:
arr3 = np.array([[2, 4, 8], [3, 9, 27]])
arr4 = np.array([[2, 4], [3, 9], [4, 16]])
arr3

array([[ 2,  4,  8],
       [ 3,  9, 27]])

In [28]:
print(arr3 + 1000)
print(arr3 * 2)


[[1002 1004 1008]
 [1003 1009 1027]]
[[ 4  8 16]
 [ 6 18 54]]


In [31]:
print(arr3 + arr3)
print(arr3 * arr3)
print(arr3 @ arr4) # 行列積

[[ 4  8 16]
 [ 6 18 54]]
[[  4  16  64]
 [  9  81 729]]
[[ 48 172]
 [141 525]]


In [33]:
print(arr3 + [100, 200, 300])
print(arr3+[[100], [200]])

[[102 204 308]
 [103 209 327]]
[[102 104 108]
 [203 209 227]]


In [37]:
print(arr3.sum())
print(arr3.sum(axis=0)) # →
print(arr3.sum(axis=1)) # ↓


53
[ 5 13 35]
[14 39]


In [39]:
np.round(np.sqrt(arr3), 2)

array([[1.41, 2.  , 2.83],
       [1.73, 3.  , 5.2 ]])